# Numpy 学习

In [1]:
import numpy as np

## 1 多维数组的创建

### 1.1 np.array 数组的创建
np.array(collection)

collection 可以为list，或者 list里面包含的list（生成多维数组）

In [2]:
# 创建一个list
list1 = [1,2,3,4,5]
type(list1)

list

In [3]:
# 转换为nparray
data = np.array(list1)
type(data)

numpy.ndarray

#### list 显示

In [4]:
print(list1)

[1, 2, 3, 4, 5]


#### np数组显示
数组显示没有逗号

In [5]:
print(data)

[1 2 3 4 5]


### 1.2 数组属性
维度，大小，类型

In [6]:
# 创建一个2维数据
data = np.array([[1,2,3],[4,7,1]])
data

array([[1, 2, 3],
       [4, 7, 1]])

#### 1.2.1 维度 
ndim

In [7]:
data.ndim

2

#### 1.2.1 大小
shape

In [8]:
data.shape
# 表示这个多维数组的大小

(2, 3)

#### 1.2.3 数据类型
dtype

In [9]:
data.dtype

dtype('int32')

### 1.3 全零 或者 全一 
np.zeros(sth)  np.ones(sth)
sth 是一个元组， 用来指定大小 如 （3，4）

In [10]:
data = np.zeros((3,4))
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
data = np.ones((3,4))
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 1.4 随机数
np.random.rand(sth)
sth 为参数，不是元组

In [12]:
data = np.random.rand(4,5)
data

array([[1.56884031e-01, 4.77525181e-01, 2.37181853e-01, 4.71784317e-01,
        9.94592576e-01],
       [8.93926507e-01, 7.91414920e-01, 3.49504617e-01, 4.88946302e-04,
        7.69558379e-02],
       [7.46453122e-01, 9.86304751e-01, 3.02009025e-01, 6.83989437e-01,
        1.08988188e-01],
       [8.63766776e-01, 1.20945942e-02, 1.94691571e-01, 1.24857031e-01,
        7.43304565e-01]])

### 1.5 序列
np.arrange()

In [13]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.6转换数组形状和类型

#### 1.6.1
reshape() 改变数据类型 <br>

In [14]:
data2 = data.reshape((2,5))
# reshape 传入元组
data2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 1.6.2 
dtyoe() 查看数据类型 <br>
astype() 改变数据形状

In [15]:
data2.dtype

dtype('int32')

In [16]:
data3 = data2.astype(float)
data3.dtype

dtype('float64')

## 2 多维数组操作

### 2.1 索引与切片

In [17]:
# 创建一个4*5 连续矩阵
data = np.arange(1,21)
data = data.reshape((4,5))
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### 2.1.1切片

In [18]:
slide1 = data[:2,1:]
slide1
# 到第二行，从第二列开始
# 冒号前面包含，冒号后面不包含

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

#### 2.1.2 获得单个数据

In [19]:
#获得单个
data[3,3]

19

### 2.2 条件索引
arr[condition] <br>
多个条件组合要使用& 和 | 代表 and 和 or

#### 2.2.1 条件索引

In [20]:

# 找出数据中大于4的数据
is_gt = data > 4

In [21]:
print(is_gt)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [22]:
data[is_gt]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
# 简写
data[data >4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### 2.2.2 多种条件

In [24]:
data[(data > 4 )& (data % 2 == 0)]

array([ 6,  8, 10, 12, 14, 16, 18, 20])

### 2.3 转置
sth.T <br>
np.transpose(sth) <br>
np.swapaxes(sth,0,1) <br>
sth 是数组

In [25]:
#回顾数据
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

##### sth.T 转置

In [26]:
data.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

##### np.transpose(sth) 转置

In [27]:
np.transpose(data)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

##### np.swapaxes(sth,0,1) 转置

In [28]:
np.swapaxes(data,0,1)
# 0 行
# 1 列

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])